name: tekartik_common_assets
description: Common assets for various apps
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

dev_dependencies:
  lints: '>=4.0.0'
  test: '>=1.16.0'
